[advisories]
ignore = ["RUSTSEC-2024-0370"]

[bans]
deny = [
    "aws-lc",
    "aws-lc-rs",
    "aws-lc-sys",
    "native-tls",
    "openssl",
]
multiple-versions = "allow"

[licenses]
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "ISC",
    "MIT",
    "OpenSSL",
    "Unicode-DFS-2016",
    "Zlib",
    "MPL-2.0",
]

[[licenses.clarify]]
expression = "MIT AND ISC AND OpenSSL"
name = "ring"

[[licenses.clarify.license-files]]
hash = 3171872035
path = "LICENSE"

[sources]
allow-git = [
    "https://github.com/n0-computer/iroh-n0des.git",
    "https://github.com/n0-computer/irpc.git",
    "https://github.com/n0-computer/iroh.git",
]
